export type Character = {
    id: string;
    name: string;
    title: string;
    role: string;
    standard: boolean;
    color: string;
    description: string;
    hp: number;
    mana: number;
    attack: number;
    armor: number;
    move: number;
    range: number;
    accuracy: number;
    block: number;
    skill: {
        name: string;
        description: string;
        cost: number;
        cooldown: number;
        range: number;
        target: string;
    };
    passive: string;
};
export type Catalog = Record<string, Character>;
export type User = {
    username: string;
    email: string;
    avatar_character_id: string;
    id: number;
    name: string;
    rating: number;
    currency: number;
    wins: number;
    losses: number;
};
export type Unit = {
    id: string;
    character_id: string;
    owner_id: number;
    x: number;
    y: number;
    hp: number;
    max_hp: number;
    mana: number;
    max_mana: number;
    facing: string;
    recovery: number;
    cooldown: number;
    statuses: Record<string, number>;
};
export type State = {
    phase: "lobby" | "draft" | "deployment" | "battle" | "finished";
    players: { id: number; name: string }[];
    host_id: number;
    turn_player_id: number | null;
    turn_number: number;
    draft_picks: Record<string, string[]>;
    offers: Record<string, string[]>;
    pool: Record<string, string[]>;
    units: Unit[];
    ready: number[];
    active_unit_id: string | null;
    moved: boolean;
    acted: boolean;
    winner_id: number | null;
    finish_reason?: string;
    expired_player_ids?: number[];
    log: { turn: number; text: string }[];
    reward_candidates: Record<string, string[]>;
    rewards?: Record<string, { currency: number; rating_delta: number }>;
};
export type Game = {
    id: string;
    code: string;
    name: string;
    ranked: boolean;
    mode: "multiplayer" | "practice";
    time_control: "live" | "correspondence";
    turn_due_at: string | null;
    version: number;
    state: State;
    created_at: string;
    reward_claimed?: boolean;
};
export type Shared = {
    auth: { user: User | null };
    flash?: { message?: string };
    catalog: Catalog;
    [key: string]: unknown;
};
